### ISSUE TITLE
jsreport integrating in angular app

### ISSUE THREAD

**Issue by riteshdesai12** [jsreport/jsreport-browser-client-dist#8]
I want to integrate report from jsreport in agnular 2. 
Please provide your suggestions and How do I  integrate jsreport compoment in my angular app

**Comment by jamyrcarrasco** [comment]
I have few hours looking for an answer so I can use jsreport with my angular app but I think it's not possible.

**Comment by bjrmatos** [comment]
hi! it should be possible, i don't see any limitation in which it can not be possible, we don't have someone in our team that knows angular well, so that is why there is no official example.

in the end, we offer a framework agnostic solution for browser integration in this repository, it involves just doing a normal AJAX request, however i don't know which kind of problems causes doing a normal AJAX request outside of angular's $http api.

even if the framework agnostic solution that we provide does not work in angular, then you can just fallback to do a request with angular http api, here are the details about the request you need to do, both for [.render](https://github.com/jsreport/jsreport-browser-client-dist/blob/master/src/jsreport.js#L286) or [.renderAsync](https://github.com/jsreport/jsreport-browser-client-dist/blob/master/src/jsreport.js#L311), it should be easy to inspect the code a bit to figure it out how you can translate an `XMLHttpRequest` request to angular's $http.

if you figure it and made the integration to happen, please consider share with us an example (maybe in some online editor like [codesandbox](https://codesandbox.io)), it can help other users with the same problem. thanks.
